name:                simple-pango
version:             0.1.0.2
github:              "YoshikuniJujo/simple-pango"
license:             BSD3
author:              "Yoshikuni Jujo"
maintainer:          "yoshikuni.jujo@gmail.com"
copyright:           "2021 Yoshikuni Jujo"

extra-source-files:
- README.md
- ChangeLog.md
- include/pango_log_attr.h

# Metadata used when publishing your package
synopsis:            Binding to Pango library
category:            Graphics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/simple-pango#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- array
- containers
- bytestring
- text
- primitive
- c-enum
- c-struct
- union-angle
- simple-cairo
- union-color
- glib-stopgap

library:
  source-dirs: src
  include-dirs: include
  c-sources:
  - csrc/pango_log_attr.c
  pkg-config-dependencies:
  - pangocairo
  - gobject-2.0

tests:
  simple-pango-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simple-pango
